[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=3
lib_deps =
    ; Descomentar según los sensores elegidos
    ; adafruit/Adafruit SHT31 Library
    ; milesburton/DallasTemperature
    ; adafruit/Adafruit MPU6050
    ; mikalhart/TinyGPSPlus
    ; knolleary/PubSubClient
